project:
  type: website
  output-dir: docs
  resources:
    - bgiw_program.pdf
    - Grawe_CV_en.pdf

website:
  title: "Alexander Grawe"
  favicon: "/files/favicon-32x32.png"
  search: false
  google-analytics: 
    tracking-id: "G-ZRYLHTQ3PF"
    storage: none
    

  navbar:
    left:
      - text: Home  
        href: index.qmd
      - research.qmd
      - teaching.qmd
      - cv.qmd
    
    right:
      - icon: envelope-at
        href: mailto:agrawe@diw.de
        target: _blank
      - icon: github
        href: https://github.com/agrawe
        target: _blank
      - icon: twitter
        href: https://twitter.com/alex_grw
        target: _blank
      - icon: bluesky
        href: https://bsky.app/profile/agrawe.eu
        target: _blank

  page-footer: 
    left:
      - icon: c-circle
        text: 2026 Alexander Grawe<br /> This website was created using Quarto. It is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [simplex, simplex_light.scss]
      dark: [simplex, simplex_dark.scss]
    css: styles.css
    toc: false
    page-layout: full



